config/routes.rb
LavalandNew::Application.routes.draw do

  resources :comments

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :events

  resources :articles

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show
  

   match ':controller(/:action(/:id(.:format)))'
end

app/models/article.rb
class Article < ActiveRecord::Base

	acts_as_commentable
	
	
	acts_as_taggable_on :tags
    scope :by_publish_date, :order => "created_at DESC"
    
	belongs_to :user
	has_many :comments
	has_attached_file :photo, :styles => { :display => "400x300", :thumb => "200x200" }
	
end

app/models/event.rb
class Event < ActiveRecord::Base

    scope :by_publish_date, :order => "created_at DESC"
	
	acts_as_commentable
	
	
	acts_as_taggable_on :tags
    scope :by_publish_date, :order => "created_at DESC"
    
	belongs_to :user
	has_many :comments
	has_attached_file :photo, :styles => { :display => "400x300", :thumb => "200x200" }
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  acts_as_tagger
  
  has_many :articles
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include FrontendHelpers::Html5Helper
  
   protected

      def ckeditor_pictures_scope(options = {})
        ckeditor_filebrowser_scope(options)
      end

      def ckeditor_attachment_files_scope(options = {})
        ckeditor_filebrowser_scope(options)
		
      end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
	@articles = Article.tagged_with(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
	  format.js { render_to_facebox }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  
    @comment = Comment.new
    @article = Article.find(params[:id])
	commentable = Article.find(params[:id])
	@comments = commentable.comments.recent.limit(10).all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
	  format.js { render_to_facebox }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
	  format.js { render_to_facebox }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :ok }
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.json
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @articles = Article.all
	@events = Event.all
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/events_helper.rb
module EventsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.haml
%p= @curent_user

= form_for @article, :html => { :multipart => true } do |f|
  -if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg
  
  .field
    = f.label :photo
    = f.file_field :photo
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :snipit
    = f.text_area :snipit
  .field
    = f.label :content
    = f.cktext_area :content, :toolbar => 'Full', :width => 600, :height => 400
  .field
    = f.label :published
    = f.check_box :published
  .field
    = f.label :tags
    = f.text_field :tag_list
    <input type="hidden" value= "#{current_user.object_id}" name="user_id" />
  .actions
    = f.submit 'Save'

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
<br />
- @articles.each do |article|
  #home_page_article
    .color_bar_photo
    #image_box
      = image_tag "#{article.photo(:thumb)}"
    #content_box
      = link_to article.title, :controller => 'articles', :action => 'show', :id => article.id
      %p #{article.snipit}

app/views/articles/new.html.haml
%h1 New article

= render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

#image_box
  = image_tag "#{@article.photo(:display)}"
  %p.caption Photo Credit: Stephanie Brig
  %p.author #{@article.user}

#title_and_snipit_box
  %h1.title #{@article.title}
  %p #{@article.snipit}


%p.article_content #{@article.content}

- @article.tag_list.each do |tag|
  = link_to tag, :action => "index", :id => tag
    


%hr

%h3 Add A Comment

= form_tag(:controller => "comments", :action => "create", :method => "post", :name => "comment") do |f|
  .field
    = label_tag :content
    = text_area_tag(:comment, "", :size => "50x6")
  .actions
    = submit_tag 'Save'

 
  
%h3== Comments for #{@article.title}:
%ul
  - @article.comments.each do |comment|
    %p= comment.comment
 

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path

app/views/events/_form.html.haml
= form_for @event do |f|
  -if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :location
    = f.text_field :location
  .field
    = f.label :date_and_time
    = f.datetime_select :date_and_time
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :tags
    = f.text_field :tag_list
    <input type="hidden" value= "#{current_user.id}" name="user_id" />
  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events

%table

  - @events.each do |event|
    %tr
      %td= event.title
      %td= event.location
      %td= event.date_and_time
      %td= event.description
      %td= link_to 'Read More', event
%br

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Location:
  = @event.location
%p
  %b Date and time:
  = @event.date_and_time
%p
  %b Description:
  = @event.description

= link_to 'Back', events_path

app/views/home/index.html.haml
#homepage_article_container
  - @articles.each do |article|
    #home_page_article
    .color_bar
    #homepage_article_image_container
      = image_tag "#{article.photo(:thumb)}"
    #homepage_article_article_content
      %p= link_to article.title, articles_path(article.id), :data => { :colorbox => true, :colorbox_height => '900px', :colorbox_width => '980px'}
      %p #{article.snipit}
#homepage_add_user_content_container
  = link_to 'Add Article - ', new_article_path, :data => { :colorbox => true, :colorbox_height => '600px', :colorbox_width => '600px'}
  = link_to 'Add Event', new_event_path, :data => { :colorbox => true, :colorbox_height => '400px', :colorbox_width => '400px'}
#homepage_events_container
  %h3 Upcoming Events
  - @events.each do |event|
    %tr
      %td= event.title
      %td= event.location
      %td= event.date_and_time
      %td= link_to 'Read More', event
#homepage_links_container
  %h3 Links
  %ul
    %li= link_to 'Aquabear Legion', "http://www.aquabearlegion.com/"
    %li= link_to 'ARTS/West', "http://artswest.blogspot.com/"
    %li= link_to 'Dairy Barn', "http://www.dairybarn.org/"
    %li= link_to 'Kennedy Museum of Art', "http://www.ohio.edu/museum/"
    %li= link_to 'Gnarly As I Wanna Be', "http://gnarlyasiwannabe.com/"

app/views/layouts/application.html.haml
- html_tag class: 'no-js' do
  %head
    %title lavaland
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    = stylesheet_link_tag :application
    = stylesheet_link_tag "colorbox"
    = javascript_include_tag :application
    = javascript_include_tag "jquery.colorbox"
    = javascript_include_tag "javascripts/ckeditor/ckeditor"
    = csrf_meta_tags
  %body{:class => params[:controller]}
    #page
      #logo 
        = link_to "LAVALAND", :controller => "home", :action => "index"
      #sub_logo_container
        #sub_logo_left connect | create | converse
        #sub_logo_right Arts in Athens Ohio
      #container.container
        %header
          %nav
            %ul.hmenu
              = render 'shared/navigation'
          - flash.each do |name, msg|
            = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
        #main{:role => "main"}
          = yield
        %footer

app/views/shared/_navigation.html.haml
%li
  = link_to('Art  ', :controller => "articles", :action => "index", :id => "art")
%li
  = link_to('Photography  ', :controller => "articles", :action => "index", :id => "photography")
%li
  = link_to('Music  ', :controller => "articles", :action => "index", :id => "music")
%li
  = link_to('Reviews  ', :controller => "articles", :action => "index", :id => "review")
%li
  = link_to('Events  - ', :controller => "events", :action => "index", :id => "event")
- if user_signed_in?
  %li
    = link_to('Edit Account  - ', edit_user_registration_path)
  %li
    = link_to('Logout', destroy_user_session_path, :method=>'delete')
- else
  %li
    = link_to('Login  - ', new_user_session_path, )
  %li
    = link_to('Sign up', new_user_registration_path)

app/views/users/show.html.haml
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}